server:
  port: 0

spring:
  application:
    name: auth-service
#  zipkin:
#    base-url: http://localhost:9411/
  data:
    mongodb:
      database: auth-service
      uri: mongodb://localhost:27017/todo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#management.tracing.sampling.probability: 1.0